replicaCount: 1

image:
  repository: cs490group6/flask-good-eatz-pharmacy
  pullPolicy: Always
  tag: "latest"

db:
  secretName: backend-db-creds

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 5001
  nodePort: 30002

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /api/hello
    port: http
readinessProbe:
  httpGet:
    path: /api/hello
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []


nodeSelector: {}

tolerations: []

affinity: {}
