# templates/restart-hook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: restart-good-eatz-pharmacy-flask
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      restartPolicy: Never
      containers:
        - name: restart
          image: bitnami/kubectl:1.27
          command:
            - /bin/sh
            - -c
            - kubectl rollout restart deployment good-eatz-pharmacy-flask -n good-eatz-system
