name: CI – Pharmacy Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "no requirements.txt"
          pip install pytest pytest-cov
          python -m pip install --upgrade pip
          pip install Flask mysql-connector-python flask-cors
          pip install pytest pytest-cov
          python -m pip install --upgrade pip
          pip install Flask mysql-connector-python flask-cors
          pip install pytest pytest-cov

      - name: Run tests & enforce 60% coverage
        run: |
          pytest --cov=./ --cov-report=term-missing --cov-fail-under=60